apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-whoami
  namespace: flux-system
spec:
  targetNamespace: whoami
  interval: 1m
  path: ./apps/services/whoami
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
