apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-renovate
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/services/renovate
  prune: true
  dependsOn:
    - name: infra-sealed-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: renovate
