apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-http-echo
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/services/http-echo
  prune: true
  dependsOn:
  - name: infra-traefik  
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: http-echo
  wait: true
