apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate
  namespace: flux-system
spec:
  dependsOn:
    - name: sealed-secrets
  interval: 5m
  path: ./apps/services/renovate
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: renovate
