apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-traefik
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/traefik
  prune: true
  dependsOn:
    - name: infra-metallb
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
