apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-grafana
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/grafana
  prune: true
  dependsOn:
    - name: infra-victoria-metrics
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
