apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-rancher
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/rancher
  prune: true
  dependsOn:
  - name: infra-traefik
  sourceRef:
    kind: GitRepository
    name: flux-system
