apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-system
  namespace: flux-system
spec:
  targetNamespace: longhorn-system
  interval: 10m
  path: ./infrastructure/longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
