apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-trivvy
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/trivvy
  prune: true
  dependsOn:
    - name: infra-vl
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
