apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cert-manager-crds
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/cert-manager/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
