apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: http-echo
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/services/kube-db-test
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kube-db-test
  wait: true
