apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lab
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/lab
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 2m
  dependsOn:
    - name: cert-manager-crds
    - name: cert-manager
    - name: metallb-crds