apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-crds
  namespace: flux-system
spec:
  interval: 5m
  path: ./../../infrastructure/metallb/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
