apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-k3s-gitops-flux
  targetNamespace: kube-system
