apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-capacitor
  namespace: flux-capacitor
spec:
  interval: 5m
  chart:
    spec:
      chart: flux-capacitor
      version: '>=0.5.0'
      sourceRef:
        kind: HelmRepository
        name: flux-capacitor
        namespace: flux-capacitor
  values:
    dashboard:
      enabled: true
    resources:
      limits:
        memory: 128Mi
        cpu: 100m
