apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  targetNamespace: monitoring
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 7.3.9
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    adminUser: admin
    adminPassword: admin
    envFromSecrets: [] 
  
    service:
      type: ClusterIP
      port: 80
      targetPort: 3000

    persistence:
      enabled: true
      storageClassName: longhorn
      accessModes: ["ReadWriteOnce"]
      size: 5Gi

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: VictoriaLogs
            type: loki
            url: http://monitoring-infra-vl-victoria-logs-single-server:9428
            access: proxy
            jsonData:
              maxLines: 1000

          - name: VictoriaMetrics
            type: prometheus
            url: http://monitoring-infra-vm-victoria-metrics-single-server:8428
            access: proxy
            isDefault: true

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default

    dashboards:
      default:
        node-exporter:
          gnetId: 1860
          revision: 27
          datasource: VictoriaMetrics

    sidecar:
      dashboards:
        enabled: true
      datasources:
        enabled: true
