# infrastructure/grafana/helm-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 7.3.9
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    service:
      type: ClusterIP

    persistence:
      enabled: true
      storageClassName: longhorn
      accessModes: ["ReadWriteOnce"]
      size: 5Gi

    admin:
      existingSecret: grafana-admin

    datasources:
      enabled: true
      datasources:
      
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: VictoriaMetrics
              type: prometheus
              url: http://victoriametrics-victoria-metrics-single-server:8428
              access: proxy
              isDefault: true

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default

    dashboards:
      default:
        node-exporter:
          gnetId: 1860
          revision: 27
          datasource: VictoriaMetrics

    sidecar:
      dashboards:
        enabled: true
      datasources:
        enabled: true
