# infrastructure/promtail/helm-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: 6.15.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    config:
      clients:
        - url: http://victorialogs-victoria-logs-single-server:9428/loki/api/v1/push?_stream_fields=instance,job,host,app
      positions:
        filename: /run/promtail/positions.yaml
      scrape_configs:
        - job_name: kubernetes-pods
          pipeline_stages:
            - docker: {}
          static_configs:
            - targets:
                - localhost
              labels:
                job: kubernetes-pods
                __path__: /var/log/pods/*/*/*.log

