apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  targetNamespace: monitoring
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: 6.15.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    config:
      clients:
        - url: http://monitoring-infra-vl-victoria-logs-single-server:9428/insert/loki/api/v1/push
      positions:
        filename: /run/promtail/positions.yaml
      scrape_configs:
        - job_name: kubernetes-pods
          pipeline_stages:
            - docker: {}
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_node_name]
              target_label: host
            - source_labels: [__meta_kubernetes_pod_annotation_promtail_io_scrape]
              action: keep
              regex: true
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_name]
              target_label: pod
            - source_labels: [__meta_kubernetes_pod_container_name]
              target_label: container
            - action: replace
              replacement: /var/log/pods/*$1/*.log
              source_labels:
                - __meta_kubernetes_pod_uid
              target_label: path