apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  targetNamespace: monitoring
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: 6.15.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
#    extraArgs:
#      - -log.level=debug

    config:
      clients:
        - url: http://monitoring-infra-vl-victoria-logs-single-server:9428/insert/loki/api/v1/push
      positions:
        filename: /run/promtail/positions.yaml
      scrape_configs:
        - job_name: kubernetes-pods
          pipeline_stages: []
          static_configs:
            - targets:
                - localhost
              labels:
                job: kubernetes-pods
                __path__: /var/log/pods/*/*/*.log
