apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  targetNamespace: monitoring
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: 6.15.0
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0

    extraVolumes:
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers

    extraVolumeMounts:
      - name: varlogcontainers
        mountPath: /var/log/containers
        readOnly: true

    config:
      logLevel: debug
      serverPort: 3101
      lokiAddress: http://monitoring-infra-vl-victoria-logs-single-server:9428/insert/loki/api/v1/push

      snippets:
        scrapeConfigs: |
          - job_name: all-containers
            static_configs:
              - targets:
                  - localhost
                labels:
                  job: varlogs
                  __path__: /var/log/containers/*.log

          - job_name: kubernetes-pods
            kubernetes_sd_configs:
              - role: pod
            pipeline_stages:
              - static_labels:
                  log_type: raw
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_name]
                regex: monitoring-promtail.*
                action: drop
              - source_labels: [__meta_kubernetes_pod_container_init]
                regex: "true"
                action: drop
              - source_labels: [__meta_kubernetes_pod_annotation_promtail_io_scrape]
                action: keep
                regex: true
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                action: keep
                regex: true
              - source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              - source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
              - source_labels: [__meta_kubernetes_pod_container_name]
                target_label: container

      file: |
        server:
          http_listen_port: {{ .Values.config.serverPort }}
          log_level: {{ .Values.config.logLevel }}

        clients:
          - url: {{ .Values.config.lokiAddress }}

        positions:
          filename: /run/promtail/positions.yaml

        scrape_configs:
        {{- tpl .Values.config.snippets.scrapeConfigs . | nindent 2 }}
