apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubernetes-dashboard
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: kubernetes-dashboard
  install:
    createNamespace: true
    disableOpenAPIValidation: true
  chart:
    spec:
      chart: kubernetes-dashboard
      version: 7.11.0
      sourceRef:
        kind: HelmRepository
        name: kubedbtest  # The repo name from the HelmRepository definition
        namespace: flux-system
  values:
    hostname: dashboard.lab.local
    ingress:
      enabled: true
      ingressClassName: traefik
      tls:
        source: self-signed
