apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-values
  namespace: monitoring
data:
  values.yaml: |
    namespace: monitoring
    loki:
      persistence:
        enabled: true
        size: 10Gi
        storageClassName: default
      service:
        type: ClusterIP
      ingester:
        replicaCount: 1
