apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  releaseName: loki
  chart:
    spec:
      chart: loki-stack
      version: 2.9.9
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  interval: 10m
  values:
    namespace: monitoring
    loki:
      persistence:
        enabled: true
        size: 10Gi
        storageClassName: default
      service:
        type: ClusterIP
      ingester:
        replicaCount: 1
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
    promtail:
      podSecurityPolicy:
        enabled: false
    grafana:
      podSecurityPolicy:
        enabled: false
    prometheus:
      podSecurityPolicy:
        enabled: false    