apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infra-longhorn
  namespace: flux-system
spec:
  targetNamespace: infra-longhorn
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.6.1 # or latest
      sourceRef:
        kind: HelmRepository
        name: infa-longhorn
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: longhorn-values
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3