apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.6.1 # or latest
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
  valuesFrom:
    - kind: ConfigMap
      name: longhorn-values
