apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 12h
  chart:
    spec:
      chart: sealed-secrets
      version: 2.13.3
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  targetNamespace: kube-system
  values: {}
