apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  targetNamespace: flux-system
  interval: 12h
  chart:
    spec:
      chart: sealed-secrets
      version: 2.13.3
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  values: {}
