apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: flux-capacitor
  namespace: flux-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`flux.lab.local`)
      kind: Rule
      services:
        - name: capacitor
          port: 9000
