apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infra-traefik
  namespace: flux-system
spec:
  interval: 12h
  targetNamespace: kube-system
  chart:
    spec:
      chart: traefik
      version: 26.0.0
      sourceRef:
        kind: HelmRepository
        name: infra-traefik
        namespace: flux-system
        
  values:
    ports:
      web:
        redirectTo: websecure
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.178.2
    podAnnotations:
      promtail.io/scrape: "true"  
