apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: 26.0.0   # Renovate will track this
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    additionalArguments:
      - "--api.insecure=true"
    service:
      type: LoadBalancer
