apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infra-traefik
  namespace: kube-system
spec:
  interval: 12h
  chart:
    spec:
      chart: traefik
      version: 26.0.0
      sourceRef:
        kind: HelmRepository
        name: infra-traefik
        namespace: flux-system
  values:
    additionalArguments:
      - "--api.insecure=true"
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.178.201
