apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: apps-http-echo
  namespace: apps-http-echo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`echo.svc.lab.local`)
      kind: Rule
      services:
        - name: apps-http-echo
          port: 80
