apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher
      version: 2.8.0
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
  values:
    hostname: rancher.lab.local
    replicas: 1
    ingress:
      enabled: true
      ingressClassName: traefik
      tls:
        source: self-signed
