apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: cattle-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: rancher
      version: 2.8.5
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
  values:
    hostname: rancher.lab.local
    ingress:
      enabled: true
      ingressClassName: traefik
      tls:
        source: self-signed
