apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infra-rancher
  namespace: flux-system
spec:
  interval: 5m
  suspend: false 
  targetNamespace: cattle-system
  install:
    createNamespace: true
    disableOpenAPIValidation: true
  chart:
    spec:
      chart: rancher
      version: 2.10.3
      sourceRef:
        kind: HelmRepository
        name: infra-rancher
        namespace: flux-system
  values:
    hostname: rancher.svc.lab.local
    ingress:
      enabled: true
      ingressClassName: kube-system-infra-traefik
      tls:
        source: self-signed
