apiVersion: networking.k8s.io/v1
kind: IngressRoute
metadata:
  name: whoami
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`whoami.lab.local`)
      kind: Rule
      services:
        - name: whoami
          port: 80
