server:
  extraArgs:
    httpListenAddr: ":8428"
    loggerLevel: INFO
    envflag.enable: ""
    promscrape.config: /config/prometheus.yml
  retentionPeriod: 1
  volumeMounts:
    - name: scrape-config
      mountPath: /config
  volumes:
    - name: scrape-config
      configMap:
        name: vm-scrape-config
  persistentVolume:
    enabled: true
    storageClass: longhorn
    size: 10Gi
  service:
    type: ClusterIP
