apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoriametrics
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: victoria-metrics-single
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  values:
    server:
      retentionPeriod: 1
      service:
        type: ClusterIP
      persistentVolume:
        enabled: true
        storageClass: longhorn
        size: 10Gi
    scrape:
      enabled: true
      serviceMonitor:
        enabled: true
