apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoriametrics
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: victoria-metrics-single
      version: 0.13.5
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  values:
    server:
      extraArgs:
        httpListenAddr: ":8428"
        loggerLevel: "INFO"
        envflag.enable: "true"
        promscrape.config: "/config/prometheus.yml"

      extraVolumeMounts:
        - name: scrape-config
          mountPath: /config

      extraVolumes:
        - name: scrape-config
          configMap:
            name: vm-scrape-config

      retentionPeriod: 1
      persistentVolume:
        enabled: true
        storageClass: longhorn
        size: 10Gi
      service:
        type: ClusterIP

