apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoriametrics
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: victoria-metrics-single
      version: 0.13.5
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
  values:
    server:
      retentionPeriod: 1
    extraArgs:
      httpListenAddr: ":8428"
      loggerLevel: INFO
      envflag.enable: ""
      persistentVolume:
        enabled: true
        storageClass: longhorn
        size: 10Gi
      service:
        type: ClusterIP
    scrape:
      enabled: true
      serviceMonitor:
        enabled: true
