# infrastructure/victoriametrics/static-scrape-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-scrape-config
  namespace: flux-system
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter-prometheus-node-exporter:9100']
