apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "0 6 * * *"  # every day at 06:00 UTC
  successfulJobsHistoryLimit: 1  # Keep only the last successful job
  failedJobsHistoryLimit: 1      # Keep only the last failed job
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: ghcr.io/renovatebot/renovate:latest
              env:
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-token
                      key: token
                - name: RENOVATE_REPOSITORIES
                  value: "abaas-madscience/home-k3s-gitops-flux"
                - name: LOG_LEVEL
                  value: "info"
          restartPolicy: OnFailure
