containers:
  - name: renovate
    image: ghcr.io/renovatebot/renovate:latest
    env:
      - name: RENOVATE_TOKEN
        valueFrom:
          secretKeyRef:
            name: renovate-token
            key: token
      - name: RENOVATE_REPOSITORIES
        value: "abaas-madscience/home-k3s-gitops-flux"
