apiVersion: apps/v1
kind: Deployment
metadata:
  name: renovate
  namespace: renovate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: renovate
  template:
    metadata:
      labels:
        app: renovate
    spec:
      containers:
        - name: renovate
          image: ghcr.io/renovatebot/renovate:latest
          env:
            - name: RENOVATE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: renovate-token
                  key: token
            - name: RENOVATE_REPOSITORIES
              value: "abaas-madscience/home-k3s-gitops-flux"
            - name: LOG_LEVEL
              value: "debug"
