apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infra-victoria-logs
  namespace: monitoring
spec:
  interval: 5m
  targetNamespace: monitoring
  chart:
    spec:
      chart: victoria-logs-single
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        name: infra-victoria-logs
        namespace: flux-system
  values:
    fullnameOverride: victoria-logs  
    nameOverride: victoria-logs
    statefulset:
      name: victoria-logs 
    persistence:
      enabled: true
      existingClaim: victorialogs-pvc
    service:
      type: ClusterIP
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
