apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy
  namespace: infra-trivy
spec:
  interval: 10m
  chart:
    spec:
      chart: trivy
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: flux-system
  targetNamespace: infra-trivy
  install:
    createNamespace: true
  values:
    trivy:
      command: "image"
      targets:
        - "pod"
      severity: "CRITICAL,HIGH"
      ignoreUnfixed: true
      scanners:
        - vuln
    schedule: "0 * * * *" # Every hour
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
