apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infra-metallb
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: infra-metallb
  install:
    createNamespace: true
  chart:
    spec:
      chart: metallb
      version: 0.14.9
      sourceRef:
        kind: HelmRepository
        name: infra-metallb
        namespace: flux-system
  values:
    controller:
      webhook:
        enabled: false
