apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victorialogs
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: victoria-logs-single
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        name: flux-system
        namespace: flux-system
  values:
    persistence:
      enabled: true
      existingClaim: victorialogs-pvc
    service:
      type: ClusterIP
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
